## Build Pipeline which is just the first part of the build-release
trigger:
- pr

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Run_and_publish_unit_tests
    jobs:
      - job:
        steps:
          - task: NodeTool@0
            displayName: Install Node10
            inputs:
              versionSpec: '10.x'
          - task: TfxInstaller@3
            displayName: Install Tfx - Task Builder Utilities
            inputs:
              version: "v0.7.x"
          - task: Npm@1
            displayName: Install task dependencies
            inputs:
              command: 'install'
              workingDir: 'cosmosUploadTask'
              verbose: true
          - task: Bash@3
            displayName: Compile Javascript
            inputs:
              targetType: "inline"
              script: |
                cd cosmosUploadTask
                tsc
          - task: Npm@1
            displayName: Run Tests
            inputs:
              command: 'custom'
              workingDir: 'cosmosUploadTask/tests'
              customCommand: 'test'
              verbose: true
          - task: PublishTestResults@2
            displayName: Test Results
            inputs:
              testResultsFormat: 'VSTest'
              testResultsFiles: '**/ResultsFile.xml'
